<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ["id" => 1, "province_id" => 13, "name" => "آبادان"],
            ["id" => 2, "province_id" => 17, "name" => "آباده"],
            ["id" => 3, "province_id" => 6, "name" => "آبدانان"],
            ["id" => 4, "province_id" => 18, "name" => "آبیک"],
            ["id" => 5, "province_id" => 1, "name" => "آذرشهر"],
            ["id" => 6, "province_id" => 15, "name" => "آرادان"],
            ["id" => 7, "province_id" => 4, "name" => "آران وبیدگل"],
            ["id" => 8, "province_id" => 24, "name" => "آزادشهر"],
            ["id" => 9, "province_id" => 25, "name" => "آستارا"],
            ["id" => 10, "province_id" => 25, "name" => "آستانه اشرفیه"],
            ["id" => 11, "province_id" => 28, "name" => "آشتیان"],
            ["id" => 12, "province_id" => 13, "name" => "آغاجاری"],
            ["id" => 13, "province_id" => 24, "name" => "آق قلا"],
            ["id" => 14, "province_id" => 27, "name" => "آمل"],
            ["id" => 15, "province_id" => 18, "name" => "آوج"],
            ["id" => 16, "province_id" => 31, "name" => "ابرکوه"],
            ["id" => 17, "province_id" => 29, "name" => "ابوموسی"],
            ["id" => 18, "province_id" => 14, "name" => "ابهر"],
            ["id" => 19, "province_id" => 28, "name" => "اراک"],
            ["id" => 20, "province_id" => 3, "name" => "اردبیل"],
            ["id" => 21, "province_id" => 4, "name" => "اردستان"],
            ["id" => 22, "province_id" => 31, "name" => "اردکان"],
            ["id" => 23, "province_id" => 9, "name" => "اردل"],
            ["id" => 24, "province_id" => 21, "name" => "ارزوییه"],
            ["id" => 25, "province_id" => 17, "name" => "ارسنجان"],
            ["id" => 26, "province_id" => 2, "name" => "ارومیه"],
            ["id" => 27, "province_id" => 26, "name" => "ازنا"],
            ["id" => 28, "province_id" => 17, "name" => "استهبان"],
            ["id" => 29, "province_id" => 30, "name" => "اسدآباد"],
            ["id" => 30, "province_id" => 12, "name" => "اسفراین"],
            ["id" => 31, "province_id" => 1, "name" => "اسکو"],
            ["id" => 32, "province_id" => 22, "name" => "اسلام آبادغرب"],
            ["id" => 33, "province_id" => 8, "name" => "اسلامشهر"],
            ["id" => 34, "province_id" => 5, "name" => "اشتهارد"],
            ["id" => 35, "province_id" => 31, "name" => "اشکذر"],
            ["id" => 36, "province_id" => 2, "name" => "اشنویه"],
            ["id" => 37, "province_id" => 4, "name" => "اصفهان"],
            ["id" => 38, "province_id" => 3, "name" => "اصلاندوز"],
            ["id" => 39, "province_id" => 17, "name" => "اقلید"],
            ["id" => 40, "province_id" => 18, "name" => "البرز"],
            ["id" => 41, "province_id" => 26, "name" => "الیگودرز"],
            ["id" => 42, "province_id" => 25, "name" => "املش"],
            ["id" => 43, "province_id" => 13, "name" => "امیدیه"],
            ["id" => 44, "province_id" => 21, "name" => "انار"],
            ["id" => 45, "province_id" => 13, "name" => "اندیکا"],
            ["id" => 46, "province_id" => 13, "name" => "اندیمشک"],
            ["id" => 47, "province_id" => 17, "name" => "اوز"],
            ["id" => 48, "province_id" => 1, "name" => "اهر"],
            ["id" => 49, "province_id" => 13, "name" => "اهواز"],
            ["id" => 50, "province_id" => 14, "name" => "ایجرود"],
            ["id" => 51, "province_id" => 13, "name" => "ایذه"],
            ["id" => 52, "province_id" => 16, "name" => "ایرانشهر"],
            ["id" => 53, "province_id" => 6, "name" => "ایلام"],
            ["id" => 54, "province_id" => 6, "name" => "ایوان"],
            ["id" => 55, "province_id" => 27, "name" => "بابل"],
            ["id" => 56, "province_id" => 27, "name" => "بابلسر"],
            ["id" => 57, "province_id" => 11, "name" => "باخرز"],
            ["id" => 58, "province_id" => 23, "name" => "باشت"],
            ["id" => 59, "province_id" => 13, "name" => "باغ ملک"],
            ["id" => 60, "province_id" => 21, "name" => "بافت"],
            ["id" => 61, "province_id" => 31, "name" => "بافق"],
            ["id" => 62, "province_id" => 20, "name" => "بانه"],
            ["id" => 63, "province_id" => 13, "name" => "باوی"],
            ["id" => 64, "province_id" => 11, "name" => "بجستان"],
            ["id" => 65, "province_id" => 12, "name" => "بجنورد"],
            ["id" => 66, "province_id" => 17, "name" => "بختگان"],
            ["id" => 67, "province_id" => 6, "name" => "بدره"],
            ["id" => 68, "province_id" => 4, "name" => "برخوار"],
            ["id" => 69, "province_id" => 11, "name" => "بردسکن"],
            ["id" => 70, "province_id" => 21, "name" => "بردسیر"],
            ["id" => 71, "province_id" => 26, "name" => "بروجرد"],
            ["id" => 72, "province_id" => 9, "name" => "بروجن"],
            ["id" => 73, "province_id" => 1, "name" => "بستان آباد"],
            ["id" => 74, "province_id" => 29, "name" => "بستک"],
            ["id" => 75, "province_id" => 29, "name" => "بشاگرد"],
            ["id" => 76, "province_id" => 10, "name" => "بشرویه"],
            ["id" => 77, "province_id" => 21, "name" => "بم"],
            ["id" => 78, "province_id" => 16, "name" => "بمپور"],
            ["id" => 79, "province_id" => 9, "name" => "بن"],
            ["id" => 80, "province_id" => 1, "name" => "بناب"],
            ["id" => 81, "province_id" => 25, "name" => "بندرانزلی"],
            ["id" => 82, "province_id" => 29, "name" => "بندرعباس"],
            ["id" => 83, "province_id" => 24, "name" => "بندرگز"],
            ["id" => 84, "province_id" => 29, "name" => "بندرلنگه"],
            ["id" => 85, "province_id" => 13, "name" => "بندرماهشهر"],
            ["id" => 86, "province_id" => 4, "name" => "بو یین و میاندشت"],
            ["id" => 87, "province_id" => 17, "name" => "بوانات"],
            ["id" => 88, "province_id" => 7, "name" => "بوشهر"],
            ["id" => 89, "province_id" => 2, "name" => "بوکان"],
            ["id" => 90, "province_id" => 23, "name" => "بویراحمد"],
            ["id" => 91, "province_id" => 18, "name" => "بویین زهرا"],
            ["id" => 92, "province_id" => 31, "name" => "بهاباد"],
            ["id" => 93, "province_id" => 30, "name" => "بهار"],
            ["id" => 94, "province_id" => 8, "name" => "بهارستان"],
            ["id" => 95, "province_id" => 13, "name" => "بهبهان"],
            ["id" => 96, "province_id" => 27, "name" => "بهشهر"],
            ["id" => 97, "province_id" => 23, "name" => "بهمیی"],
            ["id" => 98, "province_id" => 20, "name" => "بیجار"],
            ["id" => 99, "province_id" => 10, "name" => "بیرجند"],
            ["id" => 100, "province_id" => 17, "name" => "بیضا"],
            ["id" => 101, "province_id" => 3, "name" => "بیله سوار"],
            ["id" => 102, "province_id" => 11, "name" => "بینالود"],
            ["id" => 103, "province_id" => 3, "name" => "پارس آباد"],
            ["id" => 104, "province_id" => 29, "name" => "پارسیان"],
            ["id" => 105, "province_id" => 17, "name" => "پاسارگاد"],
            ["id" => 106, "province_id" => 8, "name" => "پاکدشت"],
            ["id" => 107, "province_id" => 22, "name" => "پاوه"],
            ["id" => 108, "province_id" => 8, "name" => "پردیس"],
            ["id" => 109, "province_id" => 26, "name" => "پلدختر"],
            ["id" => 110, "province_id" => 2, "name" => "پلدشت"],
            ["id" => 111, "province_id" => 2, "name" => "پیرانشهر"],
            ["id" => 112, "province_id" => 8, "name" => "پیشوا"],
            ["id" => 113, "province_id" => 18, "name" => "تاکستان"],
            ["id" => 114, "province_id" => 11, "name" => "تایباد"],
            ["id" => 115, "province_id" => 1, "name" => "تبریز"],
            ["id" => 116, "province_id" => 11, "name" => "تربت جام"],
            ["id" => 117, "province_id" => 11, "name" => "تربت حیدریه"],
            ["id" => 118, "province_id" => 24, "name" => "ترکمن"],
            ["id" => 119, "province_id" => 31, "name" => "تفت"],
            ["id" => 120, "province_id" => 16, "name" => "تفتان"],
            ["id" => 121, "province_id" => 28, "name" => "تفرش"],
            ["id" => 122, "province_id" => 2, "name" => "تکاب"],
            ["id" => 123, "province_id" => 27, "name" => "تنکابن"],
            ["id" => 124, "province_id" => 7, "name" => "تنگستان"],
            ["id" => 125, "province_id" => 30, "name" => "تویسرکان"],
            ["id" => 126, "province_id" => 8, "name" => "تهران"],
            ["id" => 127, "province_id" => 4, "name" => "تیران وکرون"],
            ["id" => 128, "province_id" => 22, "name" => "ثلاث باباجانی"],
            ["id" => 129, "province_id" => 12, "name" => "جاجرم"],
            ["id" => 130, "province_id" => 29, "name" => "جاسک"],
            ["id" => 131, "province_id" => 11, "name" => "جغتای"],
            ["id" => 132, "province_id" => 1, "name" => "جلفا"],
            ["id" => 133, "province_id" => 7, "name" => "جم"],
            ["id" => 134, "province_id" => 22, "name" => "جوانرود"],
            ["id" => 135, "province_id" => 27, "name" => "جویبار"],
            ["id" => 136, "province_id" => 11, "name" => "جوین"],
            ["id" => 137, "province_id" => 17, "name" => "جهرم"],
            ["id" => 138, "province_id" => 21, "name" => "جیرفت"],
            ["id" => 139, "province_id" => 4, "name" => "چادگان"],
            ["id" => 140, "province_id" => 1, "name" => "چاراویماق"],
            ["id" => 141, "province_id" => 2, "name" => "چالدران"],
            ["id" => 142, "province_id" => 27, "name" => "چالوس"],
            ["id" => 143, "province_id" => 16, "name" => "چاه بهار"],
            ["id" => 144, "province_id" => 2, "name" => "چایپاره"],
            ["id" => 145, "province_id" => 23, "name" => "چرام"],
            ["id" => 146, "province_id" => 6, "name" => "چرداول"],
            ["id" => 147, "province_id" => 26, "name" => "چگنی"],
            ["id" => 148, "province_id" => 11, "name" => "چناران"],
            ["id" => 149, "province_id" => 29, "name" => "حاجی اباد"],
            ["id" => 150, "province_id" => 13, "name" => "حمیدیه"],
            ["id" => 151, "province_id" => 31, "name" => "خاتم"],
            ["id" => 152, "province_id" => 16, "name" => "خاش"],
            ["id" => 153, "province_id" => 9, "name" => "خانمیرزا"],
            ["id" => 154, "province_id" => 1, "name" => "خداآفرین"],
            ["id" => 155, "province_id" => 14, "name" => "خدابنده"],
            ["id" => 156, "province_id" => 17, "name" => "خرامه"],
            ["id" => 157, "province_id" => 26, "name" => "خرم آباد"],
            ["id" => 158, "province_id" => 17, "name" => "خرم بید"],
            ["id" => 159, "province_id" => 14, "name" => "خرمدره"],
            ["id" => 160, "province_id" => 13, "name" => "خرمشهر"],
            ["id" => 161, "province_id" => 17, "name" => "خفر"],
            ["id" => 162, "province_id" => 3, "name" => "خلخال"],
            ["id" => 163, "province_id" => 11, "name" => "خلیل آباد"],
            ["id" => 164, "province_id" => 29, "name" => "خمیر"],
            ["id" => 165, "province_id" => 28, "name" => "خمین"],
            ["id" => 166, "province_id" => 4, "name" => "خمینی شهر"],
            ["id" => 167, "province_id" => 17, "name" => "خنج"],
            ["id" => 168, "province_id" => 28, "name" => "خنداب"],
            ["id" => 169, "province_id" => 11, "name" => "خواف"],
            ["id" => 170, "province_id" => 4, "name" => "خوانسار"],
            ["id" => 171, "province_id" => 4, "name" => "خور و بیابانک"],
            ["id" => 172, "province_id" => 10, "name" => "خوسف"],
            ["id" => 173, "province_id" => 11, "name" => "خوشاب"],
            ["id" => 174, "province_id" => 2, "name" => "خوی"],
            ["id" => 175, "province_id" => 17, "name" => "داراب"],
            ["id" => 176, "province_id" => 22, "name" => "دالاهو"],
            ["id" => 177, "province_id" => 15, "name" => "دامغان"],
            ["id" => 178, "province_id" => 11, "name" => "داورزن"],
            ["id" => 179, "province_id" => 11, "name" => "درگز"],
            ["id" => 180, "province_id" => 30, "name" => "درگزین"],
            ["id" => 181, "province_id" => 10, "name" => "درمیان"],
            ["id" => 182, "province_id" => 6, "name" => "دره شهر"],
            ["id" => 183, "province_id" => 13, "name" => "دزفول"],
            ["id" => 184, "province_id" => 13, "name" => "دشت آزادگان"],
            ["id" => 185, "province_id" => 7, "name" => "دشتستان"],
            ["id" => 186, "province_id" => 7, "name" => "دشتی"],
            ["id" => 187, "province_id" => 16, "name" => "دشتیاری"],
            ["id" => 188, "province_id" => 26, "name" => "دلفان"],
            ["id" => 189, "province_id" => 16, "name" => "دلگان"],
            ["id" => 190, "province_id" => 28, "name" => "دلیجان"],
            ["id" => 191, "province_id" => 8, "name" => "دماوند"],
            ["id" => 192, "province_id" => 23, "name" => "دنا"],
            ["id" => 193, "province_id" => 26, "name" => "دورود"],
            ["id" => 194, "province_id" => 4, "name" => "دهاقان"],
            ["id" => 195, "province_id" => 20, "name" => "دهگلان"],
            ["id" => 196, "province_id" => 6, "name" => "دهلران"],
            ["id" => 197, "province_id" => 7, "name" => "دیر"],
            ["id" => 198, "province_id" => 7, "name" => "دیلم"],
            ["id" => 199, "province_id" => 20, "name" => "دیواندره"],
            ["id" => 200, "province_id" => 21, "name" => "رابر"],
            ["id" => 201, "province_id" => 12, "name" => "راز و جرگلان"],
            ["id" => 202, "province_id" => 16, "name" => "راسک"],
            ["id" => 203, "province_id" => 27, "name" => "رامسر"],
            ["id" => 204, "province_id" => 13, "name" => "رامشیر"],
            ["id" => 205, "province_id" => 13, "name" => "رامهرمز"],
            ["id" => 206, "province_id" => 24, "name" => "رامیان"],
            ["id" => 207, "province_id" => 21, "name" => "راور"],
            ["id" => 208, "province_id" => 8, "name" => "رباط کریم"],
            ["id" => 209, "province_id" => 30, "name" => "رزن"],
            ["id" => 210, "province_id" => 17, "name" => "رستم"],
            ["id" => 211, "province_id" => 25, "name" => "رشت"],
            ["id" => 212, "province_id" => 11, "name" => "رشتخوار"],
            ["id" => 213, "province_id" => 25, "name" => "رضوانشهر"],
            ["id" => 214, "province_id" => 21, "name" => "رفسنجان"],
            ["id" => 215, "province_id" => 22, "name" => "روانسر"],
            ["id" => 216, "province_id" => 29, "name" => "رودان"],
            ["id" => 217, "province_id" => 25, "name" => "رودبار"],
            ["id" => 218, "province_id" => 21, "name" => "رودبارجنوب"],
            ["id" => 219, "province_id" => 25, "name" => "رودسر"],
            ["id" => 220, "province_id" => 26, "name" => "رومشکان"],
            ["id" => 221, "province_id" => 8, "name" => "ری"],
            ["id" => 222, "province_id" => 21, "name" => "ریگان"],
            ["id" => 223, "province_id" => 16, "name" => "زابل"],
            ["id" => 224, "province_id" => 11, "name" => "زاوه"],
            ["id" => 225, "province_id" => 16, "name" => "زاهدان"],
            ["id" => 226, "province_id" => 17, "name" => "زرقان"],
            ["id" => 227, "province_id" => 21, "name" => "زرند"],
            ["id" => 228, "province_id" => 28, "name" => "زرندیه"],
            ["id" => 229, "province_id" => 17, "name" => "زرین دشت"],
            ["id" => 230, "province_id" => 14, "name" => "زنجان"],
            ["id" => 231, "province_id" => 16, "name" => "زهک"],
            ["id" => 232, "province_id" => 10, "name" => "زیرکوه"],
            ["id" => 233, "province_id" => 27, "name" => "ساری"],
            ["id" => 234, "province_id" => 9, "name" => "سامان"],
            ["id" => 235, "province_id" => 5, "name" => "ساوجبلاغ"],
            ["id" => 236, "province_id" => 28, "name" => "ساوه"],
            ["id" => 237, "province_id" => 11, "name" => "سبزوار"],
            ["id" => 238, "province_id" => 17, "name" => "سپیدان"],
            ["id" => 239, "province_id" => 1, "name" => "سراب"],
            ["id" => 240, "province_id" => 16, "name" => "سراوان"],
            ["id" => 241, "province_id" => 10, "name" => "سرایان"],
            ["id" => 242, "province_id" => 16, "name" => "سرباز"],
            ["id" => 243, "province_id" => 10, "name" => "سربیشه"],
            ["id" => 244, "province_id" => 22, "name" => "سرپل ذهاب"],
            ["id" => 245, "province_id" => 17, "name" => "سرچهان"],
            ["id" => 246, "province_id" => 11, "name" => "سرخس"],
            ["id" => 247, "province_id" => 15, "name" => "سرخه"],
            ["id" => 248, "province_id" => 2, "name" => "سردشت"],
            ["id" => 249, "province_id" => 3, "name" => "سرعین"],
            ["id" => 250, "province_id" => 20, "name" => "سروآباد"],
            ["id" => 251, "province_id" => 17, "name" => "سروستان"],
            ["id" => 252, "province_id" => 20, "name" => "سقز"],
            ["id" => 253, "province_id" => 26, "name" => "سلسله"],
            ["id" => 254, "province_id" => 14, "name" => "سلطانیه"],
            ["id" => 255, "province_id" => 2, "name" => "سلماس"],
            ["id" => 256, "province_id" => 15, "name" => "سمنان"],
            ["id" => 257, "province_id" => 4, "name" => "سمیرم"],
            ["id" => 258, "province_id" => 22, "name" => "سنقر"],
            ["id" => 259, "province_id" => 20, "name" => "سنندج"],
            ["id" => 260, "province_id" => 27, "name" => "سوادکوه"],
            ["id" => 261, "province_id" => 27, "name" => "سوادکوه شمالی"],
            ["id" => 262, "province_id" => 25, "name" => "سیاهکل"],
            ["id" => 263, "province_id" => 16, "name" => "سیب و سوران"],
            ["id" => 264, "province_id" => 21, "name" => "سیرجان"],
            ["id" => 265, "province_id" => 6, "name" => "سیروان"],
            ["id" => 266, "province_id" => 29, "name" => "سیریک"],
            ["id" => 267, "province_id" => 27, "name" => "سیمرغ"],
            ["id" => 268, "province_id" => 13, "name" => "شادگان"],
            ["id" => 269, "province_id" => 28, "name" => "شازند"],
            ["id" => 270, "province_id" => 15, "name" => "شاهرود"],
            ["id" => 271, "province_id" => 2, "name" => "شاهین دژ"],
            ["id" => 272, "province_id" => 4, "name" => "شاهین شهرومیمه"],
            ["id" => 273, "province_id" => 1, "name" => "شبستر"],
            ["id" => 274, "province_id" => 25, "name" => "شفت"],
            ["id" => 275, "province_id" => 8, "name" => "شمیرانات"],
            ["id" => 276, "province_id" => 13, "name" => "شوش"],
            ["id" => 277, "province_id" => 13, "name" => "شوشتر"],
            ["id" => 278, "province_id" => 2, "name" => "شوط"],
            ["id" => 279, "province_id" => 21, "name" => "شهربابک"],
            ["id" => 280, "province_id" => 4, "name" => "شهرضا"],
            ["id" => 281, "province_id" => 9, "name" => "شهرکرد"],
            ["id" => 282, "province_id" => 8, "name" => "شهریار"],
            ["id" => 283, "province_id" => 17, "name" => "شیراز"],
            ["id" => 284, "province_id" => 12, "name" => "شیروان"],
            ["id" => 285, "province_id" => 11, "name" => "صالح آباد"],
            ["id" => 286, "province_id" => 22, "name" => "صحنه"],
            ["id" => 287, "province_id" => 25, "name" => "صومعه سرا"],
            ["id" => 288, "province_id" => 14, "name" => "طارم"],
            ["id" => 289, "province_id" => 5, "name" => "طالقان"],
            ["id" => 290, "province_id" => 10, "name" => "طبس"],
            ["id" => 291, "province_id" => 25, "name" => "طوالش"],
            ["id" => 292, "province_id" => 27, "name" => "عباس آباد"],
            ["id" => 293, "province_id" => 1, "name" => "عجب شیر"],
            ["id" => 294, "province_id" => 7, "name" => "عسلویه"],
            ["id" => 295, "province_id" => 24, "name" => "علی آباد کتول"],
            ["id" => 296, "province_id" => 21, "name" => "عنبرآباد"],
            ["id" => 297, "province_id" => 9, "name" => "فارسان"],
            ["id" => 298, "province_id" => 12, "name" => "فاروج"],
            ["id" => 299, "province_id" => 21, "name" => "فاریاب"],
            ["id" => 300, "province_id" => 30, "name" => "فامنین"],
            ["id" => 301, "province_id" => 17, "name" => "فراشبند"],
            ["id" => 302, "province_id" => 28, "name" => "فراهان"],
            ["id" => 303, "province_id" => 10, "name" => "فردوس"],
            ["id" => 304, "province_id" => 5, "name" => "فردیس"],
            ["id" => 305, "province_id" => 4, "name" => "فریدن"],
            ["id" => 306, "province_id" => 4, "name" => "فریدونشهر"],
            ["id" => 307, "province_id" => 27, "name" => "فریدونکنار"],
            ["id" => 308, "province_id" => 11, "name" => "فریمان"],
            ["id" => 309, "province_id" => 17, "name" => "فسا"],
            ["id" => 310, "province_id" => 4, "name" => "فلاورجان"],
            ["id" => 311, "province_id" => 16, "name" => "فنوج"],
            ["id" => 312, "province_id" => 25, "name" => "فومن"],
            ["id" => 313, "province_id" => 21, "name" => "فهرج"],
            ["id" => 314, "province_id" => 17, "name" => "فیروزآباد"],
            ["id" => 315, "province_id" => 8, "name" => "فیروزکوه"],
            ["id" => 316, "province_id" => 11, "name" => "فیروزه"],
            ["id" => 317, "province_id" => 27, "name" => "قایم شهر"],
            ["id" => 318, "province_id" => 10, "name" => "قاینات"],
            ["id" => 319, "province_id" => 8, "name" => "قدس"],
            ["id" => 320, "province_id" => 8, "name" => "قرچک"],
            ["id" => 321, "province_id" => 20, "name" => "قروه"],
            ["id" => 322, "province_id" => 18, "name" => "قزوین"],
            ["id" => 323, "province_id" => 29, "name" => "قشم"],
            ["id" => 324, "province_id" => 22, "name" => "قصرشیرین"],
            ["id" => 325, "province_id" => 16, "name" => "قصرقند"],
            ["id" => 326, "province_id" => 21, "name" => "قلعه گنج"],
            ["id" => 327, "province_id" => 19, "name" => "قم"],
            ["id" => 328, "province_id" => 11, "name" => "قوچان"],
            ["id" => 329, "province_id" => 17, "name" => "قیروکارزین"],
            ["id" => 330, "province_id" => 13, "name" => "کارون"],
            ["id" => 331, "province_id" => 17, "name" => "کازرون"],
            ["id" => 332, "province_id" => 4, "name" => "کاشان"],
            ["id" => 333, "province_id" => 11, "name" => "کاشمر"],
            ["id" => 334, "province_id" => 20, "name" => "کامیاران"],
            ["id" => 335, "province_id" => 30, "name" => "کبودرآهنگ"],
            ["id" => 336, "province_id" => 5, "name" => "کرج"],
            ["id" => 337, "province_id" => 24, "name" => "کردکوی"],
            ["id" => 338, "province_id" => 21, "name" => "کرمان"],
            ["id" => 339, "province_id" => 22, "name" => "کرمانشاه"],
            ["id" => 340, "province_id" => 11, "name" => "کلات"],
            ["id" => 341, "province_id" => 27, "name" => "کلاردشت"],
            ["id" => 342, "province_id" => 24, "name" => "کلاله"],
            ["id" => 343, "province_id" => 1, "name" => "کلیبر"],
            ["id" => 344, "province_id" => 28, "name" => "کمیجان"],
            ["id" => 345, "province_id" => 16, "name" => "کنارک"],
            ["id" => 346, "province_id" => 7, "name" => "کنگان"],
            ["id" => 347, "province_id" => 22, "name" => "کنگاور"],
            ["id" => 348, "province_id" => 17, "name" => "کوار"],
            ["id" => 349, "province_id" => 3, "name" => "کوثر"],
            ["id" => 350, "province_id" => 17, "name" => "کوه چنار"],
            ["id" => 351, "province_id" => 21, "name" => "کوهبنان"],
            ["id" => 352, "province_id" => 26, "name" => "کوهدشت"],
            ["id" => 353, "province_id" => 9, "name" => "کوهرنگ"],
            ["id" => 354, "province_id" => 11, "name" => "کوهسرخ"],
            ["id" => 355, "province_id" => 23, "name" => "کهگیلویه"],
            ["id" => 356, "province_id" => 21, "name" => "کهنوج"],
            ["id" => 357, "province_id" => 9, "name" => "کیار"],
            ["id" => 358, "province_id" => 24, "name" => "گالیکش"],
            ["id" => 359, "province_id" => 13, "name" => "گتوند"],
            ["id" => 360, "province_id" => 23, "name" => "گچساران"],
            ["id" => 361, "province_id" => 17, "name" => "گراش"],
            ["id" => 362, "province_id" => 24, "name" => "گرگان"],
            ["id" => 363, "province_id" => 15, "name" => "گرمسار"],
            ["id" => 364, "province_id" => 12, "name" => "گرمه"],
            ["id" => 365, "province_id" => 3, "name" => "گرمی"],
            ["id" => 366, "province_id" => 4, "name" => "گلپایگان"],
            ["id" => 367, "province_id" => 27, "name" => "گلوگاه"],
            ["id" => 368, "province_id" => 24, "name" => "گمیشان"],
            ["id" => 369, "province_id" => 11, "name" => "گناباد"],
            ["id" => 370, "province_id" => 7, "name" => "گناوه"],
            ["id" => 371, "province_id" => 24, "name" => "گنبدکاووس"],
            ["id" => 372, "province_id" => 22, "name" => "گیلانغرب"],
            ["id" => 373, "province_id" => 17, "name" => "لارستان"],
            ["id" => 374, "province_id" => 13, "name" => "لالی"],
            ["id" => 375, "province_id" => 17, "name" => "لامرد"],
            ["id" => 376, "province_id" => 25, "name" => "لاهیجان"],
            ["id" => 377, "province_id" => 9, "name" => "لردگان"],
            ["id" => 378, "province_id" => 4, "name" => "لنجان"],
            ["id" => 379, "province_id" => 23, "name" => "لنده"],
            ["id" => 380, "province_id" => 25, "name" => "لنگرود"],
            ["id" => 381, "province_id" => 23, "name" => "مارگون"],
            ["id" => 382, "province_id" => 25, "name" => "ماسال"],
            ["id" => 383, "province_id" => 2, "name" => "ماکو"],
            ["id" => 384, "province_id" => 12, "name" => "مانه وسملقان"],
            ["id" => 385, "province_id" => 14, "name" => "ماهنشان"],
            ["id" => 386, "province_id" => 4, "name" => "مبارکه"],
            ["id" => 387, "province_id" => 28, "name" => "محلات"],
            ["id" => 388, "province_id" => 27, "name" => "محمودآباد"],
            ["id" => 389, "province_id" => 1, "name" => "مراغه"],
            ["id" => 390, "province_id" => 24, "name" => "مراوه تپه"],
            ["id" => 391, "province_id" => 1, "name" => "مرند"],
            ["id" => 392, "province_id" => 17, "name" => "مرودشت"],
            ["id" => 393, "province_id" => 20, "name" => "مریوان"],
            ["id" => 394, "province_id" => 13, "name" => "مسجدسلیمان"],
            ["id" => 395, "province_id" => 3, "name" => "مشگین شهر"],
            ["id" => 396, "province_id" => 11, "name" => "مشهد"],
            ["id" => 397, "province_id" => 8, "name" => "ملارد"],
            ["id" => 398, "province_id" => 30, "name" => "ملایر"],
            ["id" => 399, "province_id" => 1, "name" => "ملکان"],
            ["id" => 400, "province_id" => 6, "name" => "ملکشاهی"],
            ["id" => 401, "province_id" => 17, "name" => "ممسنی"],
            ["id" => 402, "province_id" => 21, "name" => "منوجان"],
            ["id" => 403, "province_id" => 11, "name" => "مه ولات"],
            ["id" => 404, "province_id" => 2, "name" => "مهاباد"],
            ["id" => 405, "province_id" => 15, "name" => "مهدی شهر"],
            ["id" => 406, "province_id" => 17, "name" => "مهر"],
            ["id" => 407, "province_id" => 6, "name" => "مهران"],
            ["id" => 408, "province_id" => 16, "name" => "مهرستان"],
            ["id" => 409, "province_id" => 31, "name" => "مهریز"],
            ["id" => 410, "province_id" => 15, "name" => "میامی"],
            ["id" => 411, "province_id" => 2, "name" => "میاندوآب"],
            ["id" => 412, "province_id" => 27, "name" => "میاندورود"],
            ["id" => 413, "province_id" => 1, "name" => "میانه"],
            ["id" => 414, "province_id" => 31, "name" => "میبد"],
            ["id" => 415, "province_id" => 16, "name" => "میرجاوه"],
            ["id" => 416, "province_id" => 29, "name" => "میناب"],
            ["id" => 417, "province_id" => 24, "name" => "مینودشت"],
            ["id" => 418, "province_id" => 4, "name" => "نایین"],
            ["id" => 419, "province_id" => 4, "name" => "نجف آباد"],
            ["id" => 420, "province_id" => 21, "name" => "نرماشیر"],
            ["id" => 421, "province_id" => 4, "name" => "نطنز"],
            ["id" => 422, "province_id" => 5, "name" => "نظرآباد"],
            ["id" => 423, "province_id" => 2, "name" => "نقده"],
            ["id" => 424, "province_id" => 27, "name" => "نکا"],
            ["id" => 425, "province_id" => 3, "name" => "نمین"],
            ["id" => 426, "province_id" => 27, "name" => "نور"],
            ["id" => 427, "province_id" => 27, "name" => "نوشهر"],
            ["id" => 428, "province_id" => 30, "name" => "نهاوند"],
            ["id" => 429, "province_id" => 10, "name" => "نهبندان"],
            ["id" => 430, "province_id" => 17, "name" => "نی ریز"],
            ["id" => 431, "province_id" => 3, "name" => "نیر"],
            ["id" => 432, "province_id" => 11, "name" => "نیشابور"],
            ["id" => 433, "province_id" => 16, "name" => "نیک شهر"],
            ["id" => 434, "province_id" => 16, "name" => "نیمروز"],
            ["id" => 435, "province_id" => 8, "name" => "ورامین"],
            ["id" => 436, "province_id" => 1, "name" => "ورزقان"],
            ["id" => 437, "province_id" => 16, "name" => "هامون"],
            ["id" => 438, "province_id" => 22, "name" => "هرسین"],
            ["id" => 439, "province_id" => 1, "name" => "هریس"],
            ["id" => 440, "province_id" => 1, "name" => "هشترود"],
            ["id" => 441, "province_id" => 13, "name" => "هفتکل"],
            ["id" => 442, "province_id" => 6, "name" => "هلیلان"],
            ["id" => 443, "province_id" => 30, "name" => "همدان"],
            ["id" => 444, "province_id" => 13, "name" => "هندیجان"],
            ["id" => 445, "province_id" => 1, "name" => "هوراند"],
            ["id" => 446, "province_id" => 13, "name" => "هویزه"],
            ["id" => 447, "province_id" => 16, "name" => "هیرمند"],
            ["id" => 448, "province_id" => 31, "name" => "یزد"],
        ];

        $insert = array_map(function ($city) {
            $city['created_at'] = now();
            $city['updated_at'] = now();
            return $city;
        }, $cities);

        City::insert($insert);
    }
}
